[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."openai-chat"]
  timeout = 25 # seconds

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Optimización de caché para recursos estáticos
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    # 1 año de caché para CSS con hash

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    # 1 año de caché para JS con hash

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    # 1 año de caché para imágenes WebP

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    # 1 año de caché para imágenes PNG

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    # 1 año de caché para imágenes JPG

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    # 1 año de caché para fuentes

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Caché corto para el HTML principal
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    # 1 hora de caché para HTML

# Headers de seguridad y rendimiento
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://accounts.google.com https://www.gstatic.com https://www.googletagmanager.com https://apis.google.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://firebase.googleapis.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com https://www.googleapis.com https://api.openai.com https://cdn.contentful.com https://firestore.googleapis.com https://content-firestore.googleapis.com wss://firestore.googleapis.com ws://localhost:3000 ws://0.0.0.0:3000 https://region1.google-analytics.com https://www.google-analytics.com; frame-src https://accounts.google.com https://fitness-app-2fa2d.firebaseapp.com; object-src 'none'; base-uri 'self'; form-action 'self';"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    # Preload de recursos críticos
    Link = "</logo-header-96.webp>; rel=preload; as=image; type=image/webp, </imagen-inicio.webp>; rel=preload; as=image; type=image/webp"

[forms]
  [forms.contact]
    to = ["endlessgoalsnutrition@gmail.com"]
    subject = "Nuevo mensaje desde el formulario de EGN Fitness" 