[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."openai-chat"]
  timeout = 25 # seconds

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[forms]
  [forms.contact]
    to = ["endlessgoalsnutrition@gmail.com"]
    subject = "Nuevo mensaje desde el formulario de EGN Fitness" 